# Author :- Evans Kithinji
---
AWSTemplateFormatVersion: 2010-09-09
Description: Create custom VPC with custom CIDR Block and enable dnshostname, dnssupport
Resources:
  CustomVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: CutomVPC
Outputs:
  outputVPC:
    Description: A reference to the created VPC
    Value: !Ref CustomVPC
